// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4_DbDoexckORohkp7cMweGD3qdsZllAg',
    appId: '1:989449612573:web:553335b87d95e58ba445f4',
    messagingSenderId: '989449612573',
    projectId: 'findautor-app',
    authDomain: 'findautor-app.firebaseapp.com',
    storageBucket: 'findautor-app.firebasestorage.app',
    measurementId: 'G-WSCM69950K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQFfC_sEDjnD6XTmmhvR_POIXoKlD0FoE',
    appId: '1:989449612573:android:af5d8c48e727d742a445f4',
    messagingSenderId: '989449612573',
    projectId: 'findautor-app',
    storageBucket: 'findautor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhfljERfQo5xi8F77DsHAT0dIoKaVUaAo',
    appId: '1:989449612573:ios:867e3d28df94f060a445f4',
    messagingSenderId: '989449612573',
    projectId: 'findautor-app',
    storageBucket: 'findautor-app.appspot.com',
    androidClientId:
        '989449612573-emrhkrk8j9s2u3jok1p13e57d09bujdi.apps.googleusercontent.com',
    iosClientId:
        '989449612573-2revpi4h96uroivl09fc3et79i00igrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.findatutor360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4_DbDoexckORohkp7cMweGD3qdsZllAg',
    appId: '1:989449612573:web:cd651ae1264515caa445f4',
    messagingSenderId: '989449612573',
    projectId: 'findautor-app',
    authDomain: 'findautor-app.firebaseapp.com',
    storageBucket: 'findautor-app.appspot.com',
    measurementId: 'G-6T7JLVFXN8',
  );
}
